url: http://Branden-Romero.github.io
baseurl: 

# Site Settings
title: Branden Romero
description: "About Branden Romero."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
